In [1]:
#Without cluster 1 second data
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

#data = np.loadtxt('data.txt')
data_rating =pd.read_csv(r"C:\Users\KIIT\Downloads\Flip learning pedagogy DTW\For 3 sec\Labels_for_Beta_Alpha(0-1).csv", header=None)
data_rating=np.array(data_rating)
print(data_rating)

Ground_trute =  pd.read_csv(r"C:\Users\KIIT\Downloads\Flip learning pedagogy DTW\For 3 sec\similarity.csv", header=None)
Ground_trute=np.array(Ground_trute)
print(Ground_trute)
a=0

for i in range(0, len(Ground_trute)):
    print("................",(i+1))
    actual = Ground_trute[i]
    predicted = data_rating[i]
    print(actual)
    print(predicted)
    results = confusion_matrix(actual, predicted) 
  
    print ('Confusion Matrix :')
    print(results) 
    accuracy=accuracy_score(actual, predicted) 
    a+=accuracy
    print ('Accuracy Score :',accuracy)
    print ('Report : ')
    print (classification_report(actual, predicted)) 
print("Average Accuracy:",a/20)


[[0. 0. 0. 1. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 1. 1. 0. 1. 0.]
 [1. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 1. 1. 0. 1. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0. 1. 0. 1. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 1. 0. 1. 0.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 1. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0

C:\Users\KIIT\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\KIIT\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\KIIT\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\KIIT\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318:

In [2]:
import numpy as np
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, precision_score, recall_score

# assume actual and predicted are two numpy arrays of the same shape
# actual = np.array([[1, 0], [1, 1], [0, 1], [0, 0], [1, 0]])
# predicted = np.array([[1, 0], [0, 1], [0, 1], [0, 0], [1, 1]])
predicted =pd.read_csv(r"C:\Users\KIIT\Downloads\Flip learning pedagogy DTW\For 3 sec\Labels_for_Beta_Alpha(0-1).csv", header=None)
predicted=np.array(predicted)
print(predicted)

actual =  pd.read_csv(r"C:\Users\KIIT\Downloads\Flip learning pedagogy DTW\For 3 sec\similarity.csv", header=None)
actual=np.array(actual)
print(actual)
# calculate confusion matrix
cm = confusion_matrix(actual.ravel(), predicted.ravel())

# calculate accuracy
acc = accuracy_score(actual.ravel(), predicted.ravel())

# calculate precision
precision = precision_score(actual.ravel(), predicted.ravel(), average='macro')

# calculate recall
recall = recall_score(actual.ravel(), predicted.ravel(), average='macro')

# calculate f1-score
f1 = f1_score(actual.ravel(), predicted.ravel(), average='macro')

# print results
print("Confusion Matrix:\n", cm)
print("Accuracy: {:.3f}".format(acc))
print("Precision: {:.3f}".format(precision))
print("Recall: {:.3f}".format(recall))
print("F1-Score: {:.3f}".format(f1))


[[0. 0. 0. 1. 0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 1. 1. 0. 1. 0.]
 [1. 0. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 1. 1. 0. 1. 0.]
 [1. 0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 1. 0. 1. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 0. 0. 0.]
 [0. 1. 0. 1. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0. 1. 0. 1. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 0. 0. 1. 0. 1. 0.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 0. 1. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0